name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 16.x

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Check Out
        uses: actions/checkout@v3
      - name: Install Dependencies and Typecheck
        run: |
          yarn install --frozen-lockfile
          yarn typecheck
