// Generated by https://quicktype.io

import { AxiosResponse } from 'axios'

export type Response = AxiosResponse & {
    status: number;
    statusText: string;
    config: Config
    data: { data: { template: HTMLElement }}
}

export interface Config {
    timeout:                    number;
    headers:                    Record<string, string>;
    baseURL:                    string;
    url:                        string;
    params:                     Params;
    method:                     string;
}

export interface Params {
    q:              string;
    job:            number;
    career_type:    number;
    location:       string;
    page:           string;
}

export type ElementChild = HTMLElement | null

export interface HTMLElement {
    parent: ElementChild;
    prev: ElementChild;
    next: ElementChild;
    children?: ElementChild[];
    startIndex?: null | number;
    endIndex?: null | number;
    name: "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "cite" | "code" | "col" | "colgroup" | "data" | "datalist" | "dd" | "del" | "details" | "dfn" | "dialog" | "div" | "dl" | "dt" | "em" | "embed" | "fieldset" | "figcaption" | "figure" | "footer" | "form" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "header" | "hgroup" | "hr" | "html" | "i" | "iframe" | "img" | "input" | "ins" | "kbd" | "label" | "legend" | "li" | "link" | "main" | "map" | "mark" | "menu" | "meta" | "meter" | "nav" | "noscript" | "object" | "ol" | "optgroup" | "option" | "output" | "p" | "picture" | "pre" | "progress" | "q" | "rp" | "rt" | "ruby" | "s" | "samp" | "script" | "section" | "select" | "slot" | "small" | "source" | "span" | "strong" | "style" | "sub" | "summary" | "sup" | "table" | "tbody" | "td" | "template" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "track" | "u" | "ul" | "var" | "video" | "wbr"
    attribs: Attribute;
    type: 'tag' | 'text'
    namespace: string;
    data?: string;
    'x-attribsNamespace': Attribute;
    'x-attribsPrefix': Attribute;
}

export type Attribute = { [name: string]: string | object; };