// Generated by https://quicktype.io

export interface Filters {
    job_sort:       Country[];
    company_tags:   CompanyTag[];
    employee_count: Country[];
    years:          Country[];
    countries:      Country[];
    languages:      Language[];
    positions:      { [key: string]: number };
}

export interface CompanyTag {
    key:                string;
    is_multiple_choice: boolean;
    selected:           boolean;
    display:            string;
    sub_tags:           Country[];
}

export interface Country {
    selected:   boolean;
    display:    string;
    key:        string;
    locations?: Country[];
    districts?: Country[];
}

export interface Language {
    id:    number;
    lang:  string;
    text:  string;
    count: number;
}

const filters: Filters = {
    "job_sort": [
        {
            "selected": true,
            "display": "응답률순",
            "key": "company.response_rate_order"
        },
        {
            "selected": false,
            "display": "최신순",
            "key": "job.latest_order"
        },
        {
            "selected": false,
            "display": "보상금순",
            "key": "job.compensation_order"
        },
        {
            "selected": false,
            "display": "인기순",
            "key": "job.popularity_order"
        }
    ],
    "company_tags": [
        {
            "key": "10158",
            "is_multiple_choice": false,
            "selected": false,
            "display": "업계연봉수준",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "연봉업계평균이상",
                    "key": "10021"
                },
                {
                    "selected": false,
                    "display": "연봉상위1%",
                    "key": "10022"
                },
                {
                    "selected": false,
                    "display": "연봉상위2~5%",
                    "key": "10023"
                },
                {
                    "selected": false,
                    "display": "연봉상위6~10%",
                    "key": "10024"
                },
                {
                    "selected": false,
                    "display": "연봉상위11~20%",
                    "key": "10025"
                }
            ]
        },
        {
            "key": "10159",
            "is_multiple_choice": false,
            "selected": false,
            "display": "투자",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "누적투자100억이상",
                    "key": "10052"
                }
            ]
        },
        {
            "key": "10160",
            "is_multiple_choice": false,
            "selected": false,
            "display": "인원성장률",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "인원성장",
                    "key": "10026"
                },
                {
                    "selected": false,
                    "display": "인원급성장",
                    "key": "10027"
                }
            ]
        },
        {
            "key": "10161",
            "is_multiple_choice": false,
            "selected": false,
            "display": "퇴사율",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "퇴사율5%이하",
                    "key": "10036"
                },
                {
                    "selected": false,
                    "display": "퇴사율 6~10%",
                    "key": "10037"
                }
            ]
        },
        {
            "key": "10162",
            "is_multiple_choice": false,
            "selected": false,
            "display": "인원수",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "50명이하",
                    "key": "10028"
                },
                {
                    "selected": false,
                    "display": "51~300명",
                    "key": "10029"
                },
                {
                    "selected": false,
                    "display": "301~1,000명",
                    "key": "10030"
                },
                {
                    "selected": false,
                    "display": "1,001~10,000명",
                    "key": "10031"
                },
                {
                    "selected": false,
                    "display": "10,001명이상",
                    "key": "10032"
                }
            ]
        },
        {
            "key": "10163",
            "is_multiple_choice": false,
            "selected": false,
            "display": "업력",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "설립3년이하",
                    "key": "10033"
                },
                {
                    "selected": false,
                    "display": "설립4~9년",
                    "key": "10034"
                },
                {
                    "selected": false,
                    "display": "설립10년이상",
                    "key": "10035"
                }
            ]
        },
        {
            "key": "10164",
            "is_multiple_choice": true,
            "selected": false,
            "display": "근무·휴가",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "야근없음",
                    "key": "9984"
                },
                {
                    "selected": false,
                    "display": "유연근무",
                    "key": "9986"
                },
                {
                    "selected": false,
                    "display": "주35시간",
                    "key": "10041"
                },
                {
                    "selected": false,
                    "display": "주4일근무",
                    "key": "10047"
                },
                {
                    "selected": false,
                    "display": "육아휴직",
                    "key": "10044"
                },
                {
                    "selected": false,
                    "display": "출산휴가",
                    "key": "10045"
                },
                {
                    "selected": false,
                    "display": "리프레시휴가",
                    "key": "10019"
                }
            ]
        },
        {
            "key": "9948",
            "is_multiple_choice": true,
            "selected": false,
            "display": "보상",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "성과급",
                    "key": "9992"
                },
                {
                    "selected": false,
                    "display": "상여금",
                    "key": "9994"
                },
                {
                    "selected": false,
                    "display": "연말보너스",
                    "key": "10048"
                },
                {
                    "selected": false,
                    "display": "스톡옵션",
                    "key": "9993"
                }
            ]
        },
        {
            "key": "9947",
            "is_multiple_choice": true,
            "selected": false,
            "display": "기업문화",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "수평적조직",
                    "key": "9987"
                },
                {
                    "selected": false,
                    "display": "스타트업",
                    "key": "9989"
                },
                {
                    "selected": false,
                    "display": "자율복장",
                    "key": "10043"
                },
                {
                    "selected": false,
                    "display": "워크샵",
                    "key": "10049"
                },
                {
                    "selected": false,
                    "display": "반려동물",
                    "key": "9988"
                }
            ]
        },
        {
            "key": "10165",
            "is_multiple_choice": true,
            "selected": false,
            "display": "식사·간식",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "조식제공",
                    "key": "9997"
                },
                {
                    "selected": false,
                    "display": "중식제공",
                    "key": "10039"
                },
                {
                    "selected": false,
                    "display": "석식제공",
                    "key": "9996"
                },
                {
                    "selected": false,
                    "display": "시리얼",
                    "key": "9998"
                },
                {
                    "selected": false,
                    "display": "식비",
                    "key": "9999"
                },
                {
                    "selected": false,
                    "display": "음료",
                    "key": "9964"
                },
                {
                    "selected": false,
                    "display": "맥주",
                    "key": "9962"
                },
                {
                    "selected": false,
                    "display": "커피",
                    "key": "9963"
                },
                {
                    "selected": false,
                    "display": "와인",
                    "key": "9965"
                },
                {
                    "selected": false,
                    "display": "샐러드",
                    "key": "9966"
                },
                {
                    "selected": false,
                    "display": "과일",
                    "key": "9967"
                },
                {
                    "selected": false,
                    "display": "간식",
                    "key": "9968"
                }
            ]
        },
        {
            "key": "9954",
            "is_multiple_choice": true,
            "selected": false,
            "display": "편의시설",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "사내카페",
                    "key": "9961"
                },
                {
                    "selected": false,
                    "display": "사내식당",
                    "key": "9995"
                },
                {
                    "selected": false,
                    "display": "주차",
                    "key": "10050"
                },
                {
                    "selected": false,
                    "display": "수면실",
                    "key": "10014"
                },
                {
                    "selected": false,
                    "display": "휴게실",
                    "key": "10015"
                },
                {
                    "selected": false,
                    "display": "헬스장",
                    "key": "10016"
                },
                {
                    "selected": false,
                    "display": "위워크",
                    "key": "10013"
                },
                {
                    "selected": false,
                    "display": "수유실",
                    "key": "10018"
                },
                {
                    "selected": false,
                    "display": "안마의자",
                    "key": "10017"
                }
            ]
        },
        {
            "key": "9941",
            "is_multiple_choice": true,
            "selected": false,
            "display": "가족",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "어린이집",
                    "key": "9959"
                },
                {
                    "selected": false,
                    "display": "보육시설",
                    "key": "9960"
                },
                {
                    "selected": false,
                    "display": "생일선물",
                    "key": "9957"
                },
                {
                    "selected": false,
                    "display": "결혼기념일",
                    "key": "9958"
                },
                {
                    "selected": false,
                    "display": "대출지원",
                    "key": "10038"
                }
            ]
        },
        {
            "key": "9945",
            "is_multiple_choice": true,
            "selected": false,
            "display": "출퇴근",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "택시비",
                    "key": "9980"
                },
                {
                    "selected": false,
                    "display": "차량지원",
                    "key": "9981"
                },
                {
                    "selected": false,
                    "display": "원격근무",
                    "key": "9983"
                },
                {
                    "selected": false,
                    "display": "셔틀버스",
                    "key": "10040"
                },
                {
                    "selected": false,
                    "display": "기숙사",
                    "key": "10008"
                },
                {
                    "selected": false,
                    "display": "사택",
                    "key": "10046"
                },
                {
                    "selected": false,
                    "display": "재택근무",
                    "key": "9982"
                }
            ]
        },
        {
            "key": "10166",
            "is_multiple_choice": true,
            "selected": false,
            "display": "건강·여가",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "건강검진",
                    "key": "9969"
                },
                {
                    "selected": false,
                    "display": "단체보험",
                    "key": "9971"
                },
                {
                    "selected": false,
                    "display": "의료비",
                    "key": "9970"
                },
                {
                    "selected": false,
                    "display": "운동비",
                    "key": "10002"
                },
                {
                    "selected": false,
                    "display": "문화비",
                    "key": "10003"
                },
                {
                    "selected": false,
                    "display": "동호회",
                    "key": "10000"
                },
                {
                    "selected": false,
                    "display": "복지포인트",
                    "key": "10001"
                }
            ]
        },
        {
            "key": "9944",
            "is_multiple_choice": true,
            "selected": false,
            "display": "교육",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "교육비",
                    "key": "9975"
                },
                {
                    "selected": false,
                    "display": "직무교육",
                    "key": "9979"
                },
                {
                    "selected": false,
                    "display": "세미나참가비",
                    "key": "9976"
                },
                {
                    "selected": false,
                    "display": "컨퍼런스참가비",
                    "key": "9977"
                },
                {
                    "selected": false,
                    "display": "자기계발",
                    "key": "9973"
                },
                {
                    "selected": false,
                    "display": "도서구매비",
                    "key": "9972"
                },
                {
                    "selected": false,
                    "display": "스터디지원",
                    "key": "9978"
                },
                {
                    "selected": false,
                    "display": "어학교육",
                    "key": "9974"
                },
                {
                    "selected": false,
                    "display": "해외연수",
                    "key": "10051"
                }
            ]
        },
        {
            "key": "9956",
            "is_multiple_choice": true,
            "selected": false,
            "display": "기타",
            "sub_tags": [
                {
                    "selected": false,
                    "display": "산업기능요원",
                    "key": "9990"
                },
                {
                    "selected": false,
                    "display": "전문연구요원",
                    "key": "9991"
                },
                {
                    "selected": false,
                    "display": "인공지능",
                    "key": "10011"
                },
                {
                    "selected": false,
                    "display": "IoT",
                    "key": "10012"
                },
                {
                    "selected": false,
                    "display": "핀테크",
                    "key": "10009"
                },
                {
                    "selected": false,
                    "display": "푸드테크",
                    "key": "10010"
                },
                {
                    "selected": false,
                    "display": "Macbook",
                    "key": "10004"
                },
                {
                    "selected": false,
                    "display": "iMac",
                    "key": "10005"
                },
                {
                    "selected": false,
                    "display": "노트북",
                    "key": "10006"
                },
                {
                    "selected": false,
                    "display": "통신비",
                    "key": "10007"
                }
            ]
        }
    ],
    "employee_count": [
        {
            "selected": true,
            "display": "전체",
            "key": "all"
        },
        {
            "selected": false,
            "display": "1~4명",
            "key": "1~4"
        },
        {
            "selected": false,
            "display": "5~10명",
            "key": "5~10"
        },
        {
            "selected": false,
            "display": "11~50명",
            "key": "11~50"
        },
        {
            "selected": false,
            "display": "51~200명",
            "key": "51~200"
        },
        {
            "selected": false,
            "display": "201~500명",
            "key": "201~500"
        },
        {
            "selected": false,
            "display": "501~1000명",
            "key": "501~1000"
        },
        {
            "selected": false,
            "display": "1001~5000명",
            "key": "1001~5000"
        },
        {
            "selected": false,
            "display": "5001~10000명",
            "key": "5001~10000"
        },
        {
            "selected": false,
            "display": "10001명 이상",
            "key": "10001~"
        }
    ],
    "years": [
        {
            "selected": false,
            "display": "전체",
            "key": "-1"
        },
        {
            "selected": true,
            "display": "신입",
            "key": "0"
        },
        {
            "selected": false,
            "display": "1년",
            "key": "1"
        },
        {
            "selected": false,
            "display": "2년",
            "key": "2"
        },
        {
            "selected": false,
            "display": "3년",
            "key": "3"
        },
        {
            "selected": false,
            "display": "4년",
            "key": "4"
        },
        {
            "selected": false,
            "display": "5년",
            "key": "5"
        },
        {
            "selected": false,
            "display": "6년",
            "key": "6"
        },
        {
            "selected": false,
            "display": "7년",
            "key": "7"
        },
        {
            "selected": false,
            "display": "8년",
            "key": "8"
        },
        {
            "selected": false,
            "display": "9년",
            "key": "9"
        },
        {
            "selected": false,
            "display": "10년 이상",
            "key": "10"
        }
    ],
    "countries": [
        {
            "selected": false,
            "display": "전세계",
            "key": "all",
            "locations": []
        },
        {
            "selected": false,
            "display": "대만",
            "key": "tw",
            "locations": [
                {
                    "districts": [],
                    "selected": false,
                    "display": "All",
                    "key": "all"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Taipei City ",
                    "key": "taipei-city"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "New Taipei City ",
                    "key": "new-taipei-city"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Taoyuan City ",
                    "key": "taoyuan-city"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Taichung City ",
                    "key": "taichung-city"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Tainan City ",
                    "key": "tainan-city"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Kaohsiung City ",
                    "key": "kaohsiung-city"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Keelung City ",
                    "key": "keelung-city"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Hsin-chu City ",
                    "key": "hsin-chu-city"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Hsin-chu County ",
                    "key": "hsin-chu-country"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Miaoli County ",
                    "key": "miaoli-country"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Chaiyi City ",
                    "key": "chaiyi-city"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Changhua County ",
                    "key": "changhua-country"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Nantou County ",
                    "key": "nantou-country"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Yunlin County ",
                    "key": "yunlin-country"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Chaiyi County ",
                    "key": "chaiyi-country"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Pingtung County ",
                    "key": "pingtung-country"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Yalin County ",
                    "key": "yalin-country"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Hualien County ",
                    "key": "hualien-country"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Taitung County ",
                    "key": "taitung-country"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Wuhu County ",
                    "key": "wuhu-country"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Jinmen County ",
                    "key": "jinmen-country"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Matsu ",
                    "key": "matsu"
                }
            ]
        },
        {
            "selected": false,
            "display": "싱가폴",
            "key": "sg",
            "locations": [
                {
                    "districts": [],
                    "selected": false,
                    "display": "All",
                    "key": "all"
                }
            ]
        },
        {
            "selected": false,
            "display": "일본",
            "key": "jp",
            "locations": [
                {
                    "districts": [],
                    "selected": false,
                    "display": "All",
                    "key": "all"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Tokyo",
                    "key": "tokyo"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Kanagawa",
                    "key": "kanagawa"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Chiba",
                    "key": "chiba"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Aichi",
                    "key": "aichi"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Osaka",
                    "key": "osaka"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Hyogo",
                    "key": "hyogo"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Kyoto",
                    "key": "kyoto"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Fukuoka",
                    "key": "hukuoka"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Okinawa",
                    "key": "okinawa"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Hokkaido",
                    "key": "hokkaido"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Saitama",
                    "key": "saitama"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Hioshima",
                    "key": "hioshima"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Miyagi",
                    "key": "miyagi"
                },
                {
                    "districts": [],
                    "selected": false,
                    "display": "Etc",
                    "key": "etc"
                }
            ]
        },
        {
            "selected": true,
            "display": "한국",
            "key": "kr",
            "locations": [
                {
                    "districts": [],
                    "selected": false,
                    "display": "전국",
                    "key": "all"
                },
                {
                    "districts": [
                        {
                            "selected": true,
                            "display": "전체",
                            "key": "seoul.all"
                        },
                        {
                            "selected": false,
                            "display": "강남구",
                            "key": "seoul.gangnam-gu"
                        },
                        {
                            "selected": false,
                            "display": "강동구",
                            "key": "seoul.gangdong-gu"
                        },
                        {
                            "selected": false,
                            "display": "강북구",
                            "key": "seoul.gangbuk-gu"
                        },
                        {
                            "selected": false,
                            "display": "강서구",
                            "key": "seoul.gangseo-gu"
                        },
                        {
                            "selected": false,
                            "display": "관악구",
                            "key": "seoul.gwanak-gu"
                        },
                        {
                            "selected": false,
                            "display": "광진구",
                            "key": "seoul.gwangjin-gu"
                        },
                        {
                            "selected": false,
                            "display": "구로구",
                            "key": "seoul.guro-gu"
                        },
                        {
                            "selected": false,
                            "display": "금천구",
                            "key": "seoul.geumcheon-gu"
                        },
                        {
                            "selected": false,
                            "display": "노원구",
                            "key": "seoul.nowon-gu"
                        },
                        {
                            "selected": false,
                            "display": "도봉구",
                            "key": "seoul.dobong-gu"
                        },
                        {
                            "selected": false,
                            "display": "동대문구",
                            "key": "seoul.dongdaemun-gu"
                        },
                        {
                            "selected": false,
                            "display": "동작구",
                            "key": "seoul.dongjak-gu"
                        },
                        {
                            "selected": false,
                            "display": "마포구",
                            "key": "seoul.mapo-gu"
                        },
                        {
                            "selected": false,
                            "display": "서대문구",
                            "key": "seoul.seodaemun-gu"
                        },
                        {
                            "selected": false,
                            "display": "서초구",
                            "key": "seoul.seocho-gu"
                        },
                        {
                            "selected": false,
                            "display": "성동구",
                            "key": "seoul.seongdong-gu"
                        },
                        {
                            "selected": false,
                            "display": "성북구",
                            "key": "seoul.seongbuk-gu"
                        },
                        {
                            "selected": false,
                            "display": "송파구",
                            "key": "seoul.songpa-gu"
                        },
                        {
                            "selected": false,
                            "display": "양천구",
                            "key": "seoul.yangcheon-gu"
                        },
                        {
                            "selected": false,
                            "display": "영등포구",
                            "key": "seoul.yeongdeungpo-gu"
                        },
                        {
                            "selected": false,
                            "display": "용산구",
                            "key": "seoul.yongsan-gu"
                        },
                        {
                            "selected": false,
                            "display": "은평구",
                            "key": "seoul.eunpyeong-gu"
                        },
                        {
                            "selected": false,
                            "display": "종로구",
                            "key": "seoul.jongno-gu"
                        },
                        {
                            "selected": false,
                            "display": "중구",
                            "key": "seoul.jung-gu"
                        },
                        {
                            "selected": false,
                            "display": "중랑구",
                            "key": "seoul.jungnang-gu"
                        }
                    ],
                    "selected": true,
                    "display": "서울",
                    "key": "seoul"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "busan.all"
                        },
                        {
                            "selected": false,
                            "display": "강서구",
                            "key": "busan.gangseo-gu"
                        },
                        {
                            "selected": false,
                            "display": "금정구",
                            "key": "busan.gumjung-gu"
                        },
                        {
                            "selected": false,
                            "display": "남구",
                            "key": "busan.nam-gu"
                        },
                        {
                            "selected": false,
                            "display": "동구",
                            "key": "busan.dong-gu"
                        },
                        {
                            "selected": false,
                            "display": "동래구",
                            "key": "busan.dongnae-gu"
                        },
                        {
                            "selected": false,
                            "display": "부산진구",
                            "key": "busan.busanjin-gu"
                        },
                        {
                            "selected": false,
                            "display": "북구",
                            "key": "busan.buk-gu"
                        },
                        {
                            "selected": false,
                            "display": "사상구",
                            "key": "busan.sasang-gu"
                        },
                        {
                            "selected": false,
                            "display": "사하구",
                            "key": "busan.saha-gu"
                        },
                        {
                            "selected": false,
                            "display": "서구",
                            "key": "busan.seo-gu"
                        },
                        {
                            "selected": false,
                            "display": "수영구",
                            "key": "busan.suyeong-gu"
                        },
                        {
                            "selected": false,
                            "display": "연제구",
                            "key": "busan.yeonje-gu"
                        },
                        {
                            "selected": false,
                            "display": "영도구",
                            "key": "busan.yeongdo-gu"
                        },
                        {
                            "selected": false,
                            "display": "중구",
                            "key": "busan.jung-gu"
                        },
                        {
                            "selected": false,
                            "display": "해운대구",
                            "key": "busan.haeundae-gu"
                        },
                        {
                            "selected": false,
                            "display": "기장군",
                            "key": "busan.gijang-gun"
                        }
                    ],
                    "selected": false,
                    "display": "부산",
                    "key": "busan"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "daegu.all"
                        },
                        {
                            "selected": false,
                            "display": "남구",
                            "key": "daegu.nam-gu"
                        },
                        {
                            "selected": false,
                            "display": "달서구",
                            "key": "daegu.dalseo-gu"
                        },
                        {
                            "selected": false,
                            "display": "동구",
                            "key": "daegu.dong-gu"
                        },
                        {
                            "selected": false,
                            "display": "북구",
                            "key": "daegu.buk-gu"
                        },
                        {
                            "selected": false,
                            "display": "서구",
                            "key": "daegu.seo-gu"
                        },
                        {
                            "selected": false,
                            "display": "수성구",
                            "key": "daegu.suseong-gu"
                        },
                        {
                            "selected": false,
                            "display": "중구",
                            "key": "daegu.jung-gu"
                        },
                        {
                            "selected": false,
                            "display": "달성군",
                            "key": "daegu.dalseong-gun"
                        }
                    ],
                    "selected": false,
                    "display": "대구",
                    "key": "daegu"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "incheon.all"
                        },
                        {
                            "selected": false,
                            "display": "계양구",
                            "key": "incheon.gyeyang-gu"
                        },
                        {
                            "selected": false,
                            "display": "미추홀구",
                            "key": "incheon.michuhol-gu"
                        },
                        {
                            "selected": false,
                            "display": "남동구",
                            "key": "incheon.namdong-gu"
                        },
                        {
                            "selected": false,
                            "display": "동구",
                            "key": "incheon.dong-gu"
                        },
                        {
                            "selected": false,
                            "display": "부평구",
                            "key": "incheon.bupyeong-gu"
                        },
                        {
                            "selected": false,
                            "display": "서구",
                            "key": "incheon.seo-gu"
                        },
                        {
                            "selected": false,
                            "display": "연수구",
                            "key": "incheon.yeonsu-gu"
                        },
                        {
                            "selected": false,
                            "display": "중구",
                            "key": "incheon.jung-gu"
                        },
                        {
                            "selected": false,
                            "display": "강화군",
                            "key": "incheon.ganghwa-gun"
                        },
                        {
                            "selected": false,
                            "display": "옹진군",
                            "key": "incheon.ongjin-gun"
                        }
                    ],
                    "selected": false,
                    "display": "인천",
                    "key": "incheon"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "gwangju.all"
                        },
                        {
                            "selected": false,
                            "display": "광산구",
                            "key": "gwangju.gwangsan-gu"
                        },
                        {
                            "selected": false,
                            "display": "남구",
                            "key": "gwangju.nam-gu"
                        },
                        {
                            "selected": false,
                            "display": "동구",
                            "key": "gwangju.dong-gu"
                        },
                        {
                            "selected": false,
                            "display": "북구",
                            "key": "gwangju.buk-gu"
                        },
                        {
                            "selected": false,
                            "display": "서구",
                            "key": "gwangju.seo-gu"
                        }
                    ],
                    "selected": false,
                    "display": "광주",
                    "key": "gwangju"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "daejeon.all"
                        },
                        {
                            "selected": false,
                            "display": "대덕구",
                            "key": "daejeon.daedeok-gu"
                        },
                        {
                            "selected": false,
                            "display": "동구",
                            "key": "daejeon.dong-gu"
                        },
                        {
                            "selected": false,
                            "display": "서구",
                            "key": "daejeon.seo-gu"
                        },
                        {
                            "selected": false,
                            "display": "유성구",
                            "key": "daejeon.yuseong-gu"
                        },
                        {
                            "selected": false,
                            "display": "중구",
                            "key": "daejeon.jung-gu"
                        }
                    ],
                    "selected": false,
                    "display": "대전",
                    "key": "daejeon"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "ulsan.all"
                        },
                        {
                            "selected": false,
                            "display": "남구",
                            "key": "ulsan.nam-gu"
                        },
                        {
                            "selected": false,
                            "display": "동구",
                            "key": "ulsan.dong-gu"
                        },
                        {
                            "selected": false,
                            "display": "북구",
                            "key": "ulsan.buk-gu"
                        },
                        {
                            "selected": false,
                            "display": "중구",
                            "key": "ulsan.jung-gu"
                        },
                        {
                            "selected": false,
                            "display": "울주군",
                            "key": "ulsan.ulju-gun"
                        }
                    ],
                    "selected": false,
                    "display": "울산",
                    "key": "ulsan"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "sejong.all"
                        }
                    ],
                    "selected": false,
                    "display": "세종",
                    "key": "sejong"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "gyeonggi.all"
                        },
                        {
                            "selected": false,
                            "display": "수원시",
                            "key": "gyeonggi.suwon-si"
                        },
                        {
                            "selected": false,
                            "display": "고양시",
                            "key": "gyeonggi.goyang-si"
                        },
                        {
                            "selected": false,
                            "display": "성남시",
                            "key": "gyeonggi.seongnam-si"
                        },
                        {
                            "selected": false,
                            "display": "용인시",
                            "key": "gyeonggi.yongin-si"
                        },
                        {
                            "selected": false,
                            "display": "부천시",
                            "key": "gyeonggi.bucheon-si"
                        },
                        {
                            "selected": false,
                            "display": "안산시",
                            "key": "gyeonggi.ansan-si"
                        },
                        {
                            "selected": false,
                            "display": "남양주시",
                            "key": "gyeonggi.namyangju-si"
                        },
                        {
                            "selected": false,
                            "display": "안양시",
                            "key": "gyeonggi.anyang-si"
                        },
                        {
                            "selected": false,
                            "display": "화성시",
                            "key": "gyeonggi.hwaseong-si"
                        },
                        {
                            "selected": false,
                            "display": "평택시",
                            "key": "gyeonggi.pyeongtaek-si"
                        },
                        {
                            "selected": false,
                            "display": "의정부시",
                            "key": "gyeonggi.uijeongbu-si"
                        },
                        {
                            "selected": false,
                            "display": "시흥시",
                            "key": "gyeonggi.siheung-si"
                        },
                        {
                            "selected": false,
                            "display": "파주시",
                            "key": "gyeonggi.paju-si"
                        },
                        {
                            "selected": false,
                            "display": "김포시",
                            "key": "gyeonggi.gimpo-si"
                        },
                        {
                            "selected": false,
                            "display": "광명시",
                            "key": "gyeonggi.gwangmyeong-si"
                        },
                        {
                            "selected": false,
                            "display": "광주시",
                            "key": "gyeonggi.gwangju-si"
                        },
                        {
                            "selected": false,
                            "display": "군포시",
                            "key": "gyeonggi.gunpo-si"
                        },
                        {
                            "selected": false,
                            "display": "오산시",
                            "key": "gyeonggi.osan-si"
                        },
                        {
                            "selected": false,
                            "display": "이천시",
                            "key": "gyeonggi.icheon-si"
                        },
                        {
                            "selected": false,
                            "display": "양주시",
                            "key": "gyeonggi.yangju-si"
                        },
                        {
                            "selected": false,
                            "display": "안성시",
                            "key": "gyeonggi.anseong-si"
                        },
                        {
                            "selected": false,
                            "display": "구리시",
                            "key": "gyeonggi.guri-si"
                        },
                        {
                            "selected": false,
                            "display": "포천시",
                            "key": "gyeonggi.pocheon-si"
                        },
                        {
                            "selected": false,
                            "display": "의왕시",
                            "key": "gyeonggi.uiwang-si"
                        },
                        {
                            "selected": false,
                            "display": "하남시",
                            "key": "gyeonggi.hanam-si"
                        },
                        {
                            "selected": false,
                            "display": "여주시",
                            "key": "gyeonggi.yeoju-si"
                        },
                        {
                            "selected": false,
                            "display": "양평군",
                            "key": "gyeonggi.yangpyeong-gun"
                        },
                        {
                            "selected": false,
                            "display": "동두천시",
                            "key": "gyeonggi.dongducheon-si"
                        },
                        {
                            "selected": false,
                            "display": "과천시",
                            "key": "gyeonggi.gwacheon-si"
                        },
                        {
                            "selected": false,
                            "display": "가평군",
                            "key": "gyeonggi.gapyeong-gun"
                        },
                        {
                            "selected": false,
                            "display": "연천군",
                            "key": "gyeonggi.yeoncheon-gun"
                        }
                    ],
                    "selected": false,
                    "display": "경기",
                    "key": "gyeonggi"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "gangwon.all"
                        },
                        {
                            "selected": false,
                            "display": "강릉시",
                            "key": "gangwon.gangneung-si"
                        },
                        {
                            "selected": false,
                            "display": "동해시",
                            "key": "gangwon.donghae-si"
                        },
                        {
                            "selected": false,
                            "display": "삼척시",
                            "key": "gangwon.samcheok-si"
                        },
                        {
                            "selected": false,
                            "display": "속초시",
                            "key": "gangwon.sokcho-si"
                        },
                        {
                            "selected": false,
                            "display": "원주시",
                            "key": "gangwon.wonju-si"
                        },
                        {
                            "selected": false,
                            "display": "춘천시",
                            "key": "gangwon.chuncheon-si"
                        },
                        {
                            "selected": false,
                            "display": "태백시",
                            "key": "gangwon.taebaek-si"
                        },
                        {
                            "selected": false,
                            "display": "고성군",
                            "key": "gangwon.goseong-gun"
                        },
                        {
                            "selected": false,
                            "display": "양구군",
                            "key": "gangwon.yanggu-gun"
                        },
                        {
                            "selected": false,
                            "display": "양양군",
                            "key": "gangwon.yangyang-gun"
                        },
                        {
                            "selected": false,
                            "display": "영월군",
                            "key": "gangwon.yeongwol-gun"
                        },
                        {
                            "selected": false,
                            "display": "인제군",
                            "key": "gangwon.inje-gun"
                        },
                        {
                            "selected": false,
                            "display": "정선군",
                            "key": "gangwon.jeongseon-gun"
                        },
                        {
                            "selected": false,
                            "display": "철원군",
                            "key": "gangwon.cheorwon-gun"
                        },
                        {
                            "selected": false,
                            "display": "평창군",
                            "key": "gangwon.pyeongchang-gun"
                        },
                        {
                            "selected": false,
                            "display": "홍천군",
                            "key": "gangwon.hongcheon-gun"
                        },
                        {
                            "selected": false,
                            "display": "화천군",
                            "key": "gangwon.hwacheon-gun"
                        },
                        {
                            "selected": false,
                            "display": "횡성군",
                            "key": "gangwon.hoengseong-gun"
                        }
                    ],
                    "selected": false,
                    "display": "강원",
                    "key": "gangwon"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "n-chungcheong.all"
                        },
                        {
                            "selected": false,
                            "display": "제천시",
                            "key": "n-chungcheong.jecheon-si"
                        },
                        {
                            "selected": false,
                            "display": "청주시",
                            "key": "n-chungcheong.cheongju-si"
                        },
                        {
                            "selected": false,
                            "display": "충주시",
                            "key": "n-chungcheong.chungju-si"
                        },
                        {
                            "selected": false,
                            "display": "괴산군",
                            "key": "n-chungcheong.goesan-gun"
                        },
                        {
                            "selected": false,
                            "display": "단양군",
                            "key": "n-chungcheong.danyang-gun"
                        },
                        {
                            "selected": false,
                            "display": "보은군",
                            "key": "n-chungcheong.boeun-gun"
                        },
                        {
                            "selected": false,
                            "display": "영동군",
                            "key": "n-chungcheong.yeongdong-gun"
                        },
                        {
                            "selected": false,
                            "display": "옥천군",
                            "key": "n-chungcheong.okcheon-gun"
                        },
                        {
                            "selected": false,
                            "display": "음성군",
                            "key": "n-chungcheong.eumseong-gun"
                        },
                        {
                            "selected": false,
                            "display": "진천군",
                            "key": "n-chungcheong.jincheon-gun"
                        },
                        {
                            "selected": false,
                            "display": "증평군",
                            "key": "n-chungcheong.jeungpyeong-gun"
                        },
                        {
                            "selected": false,
                            "display": "청원군",
                            "key": "n-chungcheong.cheongwon-gun"
                        }
                    ],
                    "selected": false,
                    "display": "충북",
                    "key": "n-chungcheong"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "s-chungcheong.all"
                        },
                        {
                            "selected": false,
                            "display": "공주시",
                            "key": "s-chungcheong.gongju-si"
                        },
                        {
                            "selected": false,
                            "display": "논산시",
                            "key": "s-chungcheong.nonsan-si"
                        },
                        {
                            "selected": false,
                            "display": "보령시",
                            "key": "s-chungcheong.boryeong-si"
                        },
                        {
                            "selected": false,
                            "display": "서산시",
                            "key": "s-chungcheong.seosan-si"
                        },
                        {
                            "selected": false,
                            "display": "아산시",
                            "key": "s-chungcheong.asan-si"
                        },
                        {
                            "selected": false,
                            "display": "천안시",
                            "key": "s-chungcheong.cheonan-si"
                        },
                        {
                            "selected": false,
                            "display": "금산군",
                            "key": "s-chungcheong.geumsan-gun"
                        },
                        {
                            "selected": false,
                            "display": "당진시",
                            "key": "s-chungcheong.dangjin-si"
                        },
                        {
                            "selected": false,
                            "display": "부여군",
                            "key": "s-chungcheong.buyeo-gun"
                        },
                        {
                            "selected": false,
                            "display": "서천군",
                            "key": "s-chungcheong.seocheon-gun"
                        },
                        {
                            "selected": false,
                            "display": "연기군",
                            "key": "s-chungcheong.yeongi-gun"
                        },
                        {
                            "selected": false,
                            "display": "예산군",
                            "key": "s-chungcheong.yesan-gun"
                        },
                        {
                            "selected": false,
                            "display": "청양군",
                            "key": "s-chungcheong.cheongyang-gun"
                        },
                        {
                            "selected": false,
                            "display": "태안군",
                            "key": "s-chungcheong.taean-gun"
                        },
                        {
                            "selected": false,
                            "display": "홍성군",
                            "key": "s-chungcheong.hongseong-gun"
                        }
                    ],
                    "selected": false,
                    "display": "충남",
                    "key": "s-chungcheong"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "n-jeolla.all"
                        },
                        {
                            "selected": false,
                            "display": "군산시",
                            "key": "n-jeolla.gunsan-si"
                        },
                        {
                            "selected": false,
                            "display": "김제시",
                            "key": "n-jeolla.gimje-si"
                        },
                        {
                            "selected": false,
                            "display": "남원시",
                            "key": "n-jeolla.namwon-si"
                        },
                        {
                            "selected": false,
                            "display": "익산시",
                            "key": "n-jeolla.iksan-si"
                        },
                        {
                            "selected": false,
                            "display": "전주시",
                            "key": "n-jeolla.jeonju-si"
                        },
                        {
                            "selected": false,
                            "display": "정읍시",
                            "key": "n-jeolla.jeongeup-si"
                        },
                        {
                            "selected": false,
                            "display": "고창군",
                            "key": "n-jeolla.gochang-gun"
                        },
                        {
                            "selected": false,
                            "display": "무주군",
                            "key": "n-jeolla.muju-gun"
                        },
                        {
                            "selected": false,
                            "display": "부안군",
                            "key": "n-jeolla.buan-gun"
                        },
                        {
                            "selected": false,
                            "display": "순창군",
                            "key": "n-jeolla.sunchang-gun"
                        },
                        {
                            "selected": false,
                            "display": "완주군",
                            "key": "n-jeolla.wanju-gun"
                        },
                        {
                            "selected": false,
                            "display": "임실군",
                            "key": "n-jeolla.imsil-gun"
                        },
                        {
                            "selected": false,
                            "display": "장수군",
                            "key": "n-jeolla.jangsu-gun"
                        },
                        {
                            "selected": false,
                            "display": "진안군",
                            "key": "n-jeolla.jinan-gun"
                        }
                    ],
                    "selected": false,
                    "display": "전북",
                    "key": "n-jeolla"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "s-jeolla.all"
                        },
                        {
                            "selected": false,
                            "display": "광양시",
                            "key": "s-jeolla.gwangyang-si"
                        },
                        {
                            "selected": false,
                            "display": "나주시",
                            "key": "s-jeolla.naju-si"
                        },
                        {
                            "selected": false,
                            "display": "목포시",
                            "key": "s-jeolla.mokpo-si"
                        },
                        {
                            "selected": false,
                            "display": "순천시",
                            "key": "s-jeolla.suncheon-si"
                        },
                        {
                            "selected": false,
                            "display": "여수시",
                            "key": "s-jeolla.yeosu-si"
                        },
                        {
                            "selected": false,
                            "display": "강진군",
                            "key": "s-jeolla.gangjin-gun"
                        },
                        {
                            "selected": false,
                            "display": "고흥군",
                            "key": "s-jeolla.goheung-gun"
                        },
                        {
                            "selected": false,
                            "display": "곡성군",
                            "key": "s-jeolla.gokseong-gun"
                        },
                        {
                            "selected": false,
                            "display": "구례군",
                            "key": "s-jeolla.gurye-gun"
                        },
                        {
                            "selected": false,
                            "display": "담양군",
                            "key": "s-jeolla.damyang-gun"
                        },
                        {
                            "selected": false,
                            "display": "무안군",
                            "key": "s-jeolla.muan-gun"
                        },
                        {
                            "selected": false,
                            "display": "보성군",
                            "key": "s-jeolla.boseong-gun"
                        },
                        {
                            "selected": false,
                            "display": "신안군",
                            "key": "s-jeolla.sinan-gun"
                        },
                        {
                            "selected": false,
                            "display": "영광군",
                            "key": "s-jeolla.yeonggwang-gun"
                        },
                        {
                            "selected": false,
                            "display": "영암군",
                            "key": "s-jeolla.yeongam-gun"
                        },
                        {
                            "selected": false,
                            "display": "완도군",
                            "key": "s-jeolla.wando-gun"
                        },
                        {
                            "selected": false,
                            "display": "장성군",
                            "key": "s-jeolla.jangseong-gun"
                        },
                        {
                            "selected": false,
                            "display": "장흥군",
                            "key": "s-jeolla.jangheung-gun"
                        },
                        {
                            "selected": false,
                            "display": "진도군",
                            "key": "s-jeolla.jindo-gun"
                        },
                        {
                            "selected": false,
                            "display": "함평군",
                            "key": "s-jeolla.hampyeong-gun"
                        },
                        {
                            "selected": false,
                            "display": "해남군",
                            "key": "s-jeolla.haenam-gun"
                        },
                        {
                            "selected": false,
                            "display": "화순군",
                            "key": "s-jeolla.hwasun-gun"
                        }
                    ],
                    "selected": false,
                    "display": "전남",
                    "key": "s-jeolla"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "n-gyeongsang.all"
                        },
                        {
                            "selected": false,
                            "display": "경산시",
                            "key": "n-gyeongsang.gyeongsan-si"
                        },
                        {
                            "selected": false,
                            "display": "경주시",
                            "key": "n-gyeongsang.gyeongju-si"
                        },
                        {
                            "selected": false,
                            "display": "구미시",
                            "key": "n-gyeongsang.gumi-si"
                        },
                        {
                            "selected": false,
                            "display": "김천시",
                            "key": "n-gyeongsang.gimcheon-si"
                        },
                        {
                            "selected": false,
                            "display": "문경시",
                            "key": "n-gyeongsang.mungyeong-si"
                        },
                        {
                            "selected": false,
                            "display": "상주시",
                            "key": "n-gyeongsang.sangju-si"
                        },
                        {
                            "selected": false,
                            "display": "안동시",
                            "key": "n-gyeongsang.andong-si"
                        },
                        {
                            "selected": false,
                            "display": "영주시",
                            "key": "n-gyeongsang.yeongju-si"
                        },
                        {
                            "selected": false,
                            "display": "영천시",
                            "key": "n-gyeongsang.yeongcheon-si"
                        },
                        {
                            "selected": false,
                            "display": "포항시",
                            "key": "n-gyeongsang.pohang-si"
                        },
                        {
                            "selected": false,
                            "display": "고령군",
                            "key": "n-gyeongsang.goryeong-gun"
                        },
                        {
                            "selected": false,
                            "display": "군위군",
                            "key": "n-gyeongsang.gunwi-gun"
                        },
                        {
                            "selected": false,
                            "display": "봉화군",
                            "key": "n-gyeongsang.bonghwa-gun"
                        },
                        {
                            "selected": false,
                            "display": "성주군",
                            "key": "n-gyeongsang.seongju-gun"
                        },
                        {
                            "selected": false,
                            "display": "영덕군",
                            "key": "n-gyeongsang.yeongdeok-gun"
                        },
                        {
                            "selected": false,
                            "display": "영양군",
                            "key": "n-gyeongsang.yeongyang-gun"
                        },
                        {
                            "selected": false,
                            "display": "예천군",
                            "key": "n-gyeongsang.yecheon-gun"
                        },
                        {
                            "selected": false,
                            "display": "울릉군",
                            "key": "n-gyeongsang.ulleung-gun"
                        },
                        {
                            "selected": false,
                            "display": "울진군",
                            "key": "n-gyeongsang.uljin-gun"
                        },
                        {
                            "selected": false,
                            "display": "의성군",
                            "key": "n-gyeongsang.uiseong-gun"
                        },
                        {
                            "selected": false,
                            "display": "청도군",
                            "key": "n-gyeongsang.cheongdo-gun"
                        },
                        {
                            "selected": false,
                            "display": "청송군",
                            "key": "n-gyeongsang.cheongsong-gun"
                        },
                        {
                            "selected": false,
                            "display": "칠곡군",
                            "key": "n-gyeongsang.chilgok-gun"
                        }
                    ],
                    "selected": false,
                    "display": "경북",
                    "key": "n-gyeongsang"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "s-gyeongsang.all"
                        },
                        {
                            "selected": false,
                            "display": "거제시",
                            "key": "s-gyeongsang.geoje-si"
                        },
                        {
                            "selected": false,
                            "display": "김해시",
                            "key": "s-gyeongsang.gimhae-si"
                        },
                        {
                            "selected": false,
                            "display": "밀양시",
                            "key": "s-gyeongsang.miryang-si"
                        },
                        {
                            "selected": false,
                            "display": "사천시",
                            "key": "s-gyeongsang.sacheon-si"
                        },
                        {
                            "selected": false,
                            "display": "양산시",
                            "key": "s-gyeongsang.yangsan-si"
                        },
                        {
                            "selected": false,
                            "display": "진주시",
                            "key": "s-gyeongsang.jinju-si"
                        },
                        {
                            "selected": false,
                            "display": "창원시",
                            "key": "s-gyeongsang.changwon-si"
                        },
                        {
                            "selected": false,
                            "display": "통영시",
                            "key": "s-gyeongsang.tongyeong-si"
                        },
                        {
                            "selected": false,
                            "display": "거창군",
                            "key": "s-gyeongsang.geochang-gun"
                        },
                        {
                            "selected": false,
                            "display": "고성군",
                            "key": "s-gyeongsang.goseong-gun"
                        },
                        {
                            "selected": false,
                            "display": "남해군",
                            "key": "s-gyeongsang.namhae-gun"
                        },
                        {
                            "selected": false,
                            "display": "산청군",
                            "key": "s-gyeongsang.sancheong-gun"
                        },
                        {
                            "selected": false,
                            "display": "의령군",
                            "key": "s-gyeongsang.uiryeong-gun"
                        },
                        {
                            "selected": false,
                            "display": "창녕군",
                            "key": "s-gyeongsang.changnyeong-gun"
                        },
                        {
                            "selected": false,
                            "display": "하동군",
                            "key": "s-gyeongsang.hadong-gun"
                        },
                        {
                            "selected": false,
                            "display": "함안군",
                            "key": "s-gyeongsang.haman-gun"
                        },
                        {
                            "selected": false,
                            "display": "함양군",
                            "key": "s-gyeongsang.hamyang-gun"
                        },
                        {
                            "selected": false,
                            "display": "합천군",
                            "key": "s-gyeongsang.hapcheon-gun"
                        }
                    ],
                    "selected": false,
                    "display": "경남",
                    "key": "s-gyeongsang"
                },
                {
                    "districts": [
                        {
                            "selected": false,
                            "display": "전체",
                            "key": "jeju.all"
                        },
                        {
                            "selected": false,
                            "display": "서귀포시",
                            "key": "jeju.seogwipo-si"
                        },
                        {
                            "selected": false,
                            "display": "제주시",
                            "key": "jeju.jeju-si"
                        }
                    ],
                    "selected": false,
                    "display": "제주",
                    "key": "jeju"
                }
            ]
        },
        {
            "selected": false,
            "display": "기타",
            "key": "others",
            "locations": []
        }
    ],
    "languages": [
        {
            "id": 1554,
            "lang": "ko",
            "text": "Python",
            "count": 483
        },
        {
            "id": 3078,
            "lang": "ko",
            "text": "Spring Framework",
            "count": 446
        },
        {
            "id": 1698,
            "lang": "ko",
            "text": "AWS",
            "count": 439
        },
        {
            "id": 1411,
            "lang": "ko",
            "text": "Git",
            "count": 386
        },
        {
            "id": 1457,
            "lang": "ko",
            "text": "iOS",
            "count": 279
        },
        {
            "id": 1539,
            "lang": "ko",
            "text": "HTML",
            "count": 260
        },
        {
            "id": 1541,
            "lang": "ko",
            "text": "JavaScript",
            "count": 254
        },
        {
            "id": 1464,
            "lang": "ko",
            "text": "MySQL",
            "count": 250
        },
        {
            "id": 1562,
            "lang": "ko",
            "text": "SQL",
            "count": 250
        },
        {
            "id": 1459,
            "lang": "ko",
            "text": "Linux",
            "count": 226
        },
        {
            "id": 1438,
            "lang": "ko",
            "text": "Android",
            "count": 215
        },
        {
            "id": 1544,
            "lang": "ko",
            "text": "Kotlin",
            "count": 205
        },
        {
            "id": 1563,
            "lang": "ko",
            "text": "Swift",
            "count": 174
        },
        {
            "id": 1530,
            "lang": "ko",
            "text": "C / C++",
            "count": 128
        },
        {
            "id": 1552,
            "lang": "ko",
            "text": "PHP",
            "count": 123
        },
        {
            "id": 2217,
            "lang": "ko",
            "text": "Docker",
            "count": 103
        },
        {
            "id": 1469,
            "lang": "ko",
            "text": "React",
            "count": 100
        },
        {
            "id": 1412,
            "lang": "ko",
            "text": "Github",
            "count": 77
        },
        {
            "id": 3451,
            "lang": "ko",
            "text": "JPA",
            "count": 76
        },
        {
            "id": 1786,
            "lang": "ko",
            "text": "C++",
            "count": 73
        }
    ],
    "positions": {
        "개발 전체": 518,
        "웹 개발자": 873,
        "서버 개발자": 872,
        "소프트웨어 엔지니어": 10110,
        "프론트엔드 개발자": 669,
        "자바 개발자": 660,
        "안드로이드 개발자": 677,
        "C,C++ 개발자": 900,
        "데이터 엔지니어": 655,
        "Node.js 개발자": 895,
        "iOS 개발자": 678,
        "파이썬 개발자": 899,
        "DevOps / 시스템 관리자": 674,
        "시스템,네트워크 관리자": 665,
        "머신러닝 엔지니어": 1634,
        "개발 매니저": 877,
        "기술지원": 1026,
        "빅데이터 엔지니어": 1025,
        "QA,테스트 엔지니어": 676,
        "데이터 사이언티스트": 1024,
        "보안 엔지니어": 671,
        "프로덕트 매니저": 876,
        "블록체인 플랫폼 엔지니어": 1027,
        "임베디드 개발자": 658,
        "PHP 개발자": 893,
        "하드웨어 엔지니어": 672,
        ".NET 개발자": 661,
        "웹 퍼블리셔": 939,
        "DBA": 10231,
        "크로스플랫폼 앱 개발자": 10111,
        "영상,음성 엔지니어": 896,
        "그래픽스 엔지니어": 898,
        "ERP전문가": 10230,
        "CTO,Chief Technology Officer": 795,
        "VR 엔지니어": 10112,
        "BI 엔지니어": 1022,
        "루비온레일즈 개발자": 894,
        "CIO,Chief Information Officer": 793
    }
}

export default filters