'use strict';

import { Job } from "./job.types";
import { WantedResponse } from "./wanted.res.types";
import axios, { AxiosResponse } from 'axios';
import { Context, APIGatewayProxyCallback, APIGatewayEvent } from 'aws-lambda';


// Generated by https://quicktype.io

async function run(event: APIGatewayEvent, context: Context, callback: APIGatewayProxyCallback) {
    const time = new Date();
    console.log(`Your cron function "${context.functionName}" ran at ${time}`);
}

const getWantedResponse = () => {
    const init = {
        baseURL: 'https://www.wanted.co.kr',
        url: '/api/v4/jobs',
        params: {
            country: 'kr',
            tag_type_ids: 507,
            job_sort: 'job.popularity_order',
            locations: 'seoul.all',
            years: 0
        },
        method: 'GET',
        headers: {
            'accept': 'application/json, text/plain, */*',
            'accept-encoding': 'gzip, deflate, br',
            'accept-language': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
            'cache-control': 'no-cache',
            'referer': 'https://www.wanted.co.kr/wdlist/507',
            'sec-ch-ua': '"Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"',
            'sec-ch-ua-mobile': '?0',
            'sec-ch-ua-platform': '"macOS"',
            'sec-fetch-dest': 'empty',
            'sec-fetch-mode': 'cors',
            'sec-fetch-site': 'same-origin',
            'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36',
            'wanted-user-agent': 'user-web',
            'wanted-user-country': 'KR',
            'wanted-user-language': 'ko'
        }
    };
    axios(init).then((res: AxiosResponse) => {
        const wantedJob: WantedResponse = res.data
        const jobArray = wantedJob.data as Array<Job>
        jobArray.forEach((job: Job)=>{
            if (job.address.location == '서울') {
                console.log()
                console.log(`아이디 : ${job.id}`)
                console.log(`분야 : ${job.company.industry_name}`)
                console.log(`회사명 : ${job.company.name}`)
                console.log(`좋아요 : ${job.like_count}`)
                console.log(`파트 : ${job.position}`)
                console.log(`응답률 : ${job.company.application_response_stats.avg_rate}`)
                console.log(`썸네일 : ${job.title_img.thumb}`)
            }
        })
    })
}

getWantedResponse()