// Generated by https://quicktype.io

export interface Pages {
    parent: Parent;
    properties: PageStats;
}

export interface Parent {
    database_id: string;
}

export interface PageStats {
    URL: { url: null | string }
    주요업무: { rich_text: RichText[] }
    회사타입: { multi_select: Select[] }
    포지션: { rich_text: RichText[] }
    우대사항: { rich_text: RichText[] }
    좋아요: { number: number | null }
    기술스택: { multi_select: Select[] }
    회사설명: { rich_text: RichText[] }
    썸네일: { url: null | string };
    혜택및복지: { rich_text: RichText[] }
    자격요건: { rich_text: RichText[] }
    아이디: { number: number | null }
    분야: { select: Select | null }
    응답률: { number: number | null }
    회사명: { title: RichText[] }
}

export interface MultiSelect {
    multi_select: Select[];
}

export interface Select {
    name: string;
    color: string;
}

export interface RichText {
    text: Text;
    annotations: Annotations;
    plain_text: string;
    href: null;
}

export interface Annotations {
    bold: boolean;
    italic: boolean;
    strikethrough: boolean;
    underline: boolean;
    code: boolean;
    color: string;
}

export interface Text {
    content: string;
    link: null;
}
