// Generated by https://quicktype.io

import { WantedResponse } from "./job.types";
import { AxiosResponse } from 'axios'

export type Response = AxiosResponse & {
    headers:                        Headers;
    config:                         Config;
    data:                           WantedResponse;
}
export interface Config {
    timeout:          number;
    headers:          { [key: string]: string };
    baseURL:          string;
    url:              string;
    params:           Params;
    method:           string;
}

export interface Params {
    country:      string;
    tag_type_ids: number;
    job_sort:     string;
    locations:    string;
    years:        number;
    limit?:       string;
    offset?:      string;
}