// Generated by https://quicktype.io

import { Job } from "./job.types";

export interface WantedResponse {
    model_status:             null;
    links:                    Links;
    is_callable_external_job: boolean;
    data_model:               null;
    data:                     Job[];
    is_score:                 boolean;
}

export interface Links {
    prev: string;
    next: string;
}
