rules:
  quoted-strings:
    required: only-when-needed
    extra-allowed: ["{|}"]
    quote-type: any
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
  key-duplicates: {}
  octal-values:
    forbid-implicit-octal: true
